name: ci-build-and-test

on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  # Cancel in-progress runs on PR update
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -tags release -v ./...
      - name: Test
        run: make test
      - name: Upload coverage.out
        uses: PaloAltoNetworks/cov@3.0.0
        with:
          cov_mode: coverage
          cov_file: coverage.out
