name: coverage status
on:
  workflow_run:
    workflows: ["build-go"]
    types: ["completed"]
jobs:
  cov:
    steps:
      - name: Coverage status
        uses: PaloAltoNetworks/cov@3.0.0
        with:
          cov_mode: send-status
          workflow_run_id: ${{github.run_id}}
          workflow_head_sha: ${{github.sha}}
